CREATE TABLE ListeRettigheter(
 liste_id CHAR(4) DEFAULT “Re01” NOT NULL,

	S_IFMT TINYINT NOT NULL DEFAULT 0,
	S_IFSTOCK 	TINYINT NOT NULL DEFAULT 0,
	S_IFLNK 	TINYINT NOT NULL DEFAULT 0,
	S_IFREG	TINYINT NOT NULL DEFAULT 0,
	S_IFBLK 	TINYINT NOT NULL DEFAULT 0,
	S_IFDIR	TINYINT NOT NULL DEFAULT 0,
	S_IFCHR 	TINYINT NOT NULL DEFAULT 0,
	S_ISUID	TINYINT NOT NULL DEFAULT 0,
	S_ISGID 	TINYINT NOT NULL DEFAULT 0,
	S_ISVTX 	TINYINT NOT NULL DEFAULT 0,
	S_IRWXU 	TINYINT NOT NULL DEFAULT 0,
	S_IRUSR	TINYINT NOT NULL DEFAULT 0,
	S_IWUSR	TINYINT NOT NULL DEFAULT 0,
	S_IXUSR	TINYINT NOT NULL DEFAULT 0,
	S_IRWXG 	TINYINT NOT NULL DEFAULT 0,
	S_IWGRP	TINYINT NOT NULL DEFAULT 0,
	S_IXGRP  	TINYINT NOT NULL DEFAULT 0,
	S_IRWXO 	TINYINT NOT NULL DEFAULT 0,
	S_IROTH 	TINYINT NOT NULL DEFAULT 0,
	S_IWOTH TINYINT NOT NULL DEFAULT 0,
	S_IXOTH TINYINT NOT NULL DEFAULT 0, 


    PRIMARY KEY(liste_id) 
);

